# Generated by Django 5.2.4 on 2025-07-03 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('34a2ad3f-dfc3-42f3-af98-a232abe26476'), editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
