# Generated by Django 5.2.4 on 2025-07-04 19:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_balance_alter_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b3fa8558-fe9e-436e-9184-594099e619a2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
