# Generated by Django 5.2.4 on 2025-07-04 19:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('132aa076-d15e-44e1-b8e3-07a4c934b0ea'), editable=False, primary_key=True, serialize=False),
        ),
    ]
